name: Nifty Option Chain Bot

on:
  schedule:
    # Every 15 minutes, Monday–Friday (UTC). Script itself checks IST market hours.
    - cron: "*/15 * * * 1-5"
  workflow_dispatch: {}

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot (single-shot)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python nifty_bot.py
